<?php
/**
 * AttemptOutcome
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gethook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GetHook API
 *
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gethook\Model;
use \Gethook\ObjectSerializer;

/**
 * AttemptOutcome Class Doc Comment
 *
 * @category Class
 * @package  Gethook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttemptOutcome
{
    /**
     * Possible values of this enum
     */
    public const OUTCOME_PENDING = 'pending';

    public const OUTCOME_SUCCESS = 'success';

    public const OUTCOME_TIMEOUT = 'timeout';

    public const OUTCOME_NETWORK_ERROR = 'network_error';

    public const OUTCOME_HTTP4XX = 'http_4xx';

    public const OUTCOME_HTTP5XX = 'http_5xx';

    public const OUTCOME_CANCELLED = 'cancelled';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OUTCOME_PENDING,
            self::OUTCOME_SUCCESS,
            self::OUTCOME_TIMEOUT,
            self::OUTCOME_NETWORK_ERROR,
            self::OUTCOME_HTTP4XX,
            self::OUTCOME_HTTP5XX,
            self::OUTCOME_CANCELLED
        ];
    }
}


