<?php
/**
 * Event
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gethook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GetHook API
 *
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gethook\Model;

use \ArrayAccess;
use \Gethook\ObjectSerializer;

/**
 * Event Class Doc Comment
 *
 * @category Class
 * @package  Gethook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Event implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Event';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_id' => 'string',
        'attempts_count' => 'int',
        'body' => 'string',
        'created_at' => 'string',
        'created_by' => 'string',
        'direction' => '\Gethook\Model\Direction',
        'event_type' => 'string',
        'external_event_id' => 'string',
        'final_state' => 'string',
        'headers' => 'array<string,mixed>',
        'id' => 'string',
        'next_attempt_at' => 'string',
        'payload_hash' => 'string',
        'received_at' => 'string',
        'source_id' => 'string',
        'status' => '\Gethook\Model\EventStatus'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_id' => null,
        'attempts_count' => null,
        'body' => null,
        'created_at' => null,
        'created_by' => null,
        'direction' => null,
        'event_type' => null,
        'external_event_id' => null,
        'final_state' => null,
        'headers' => null,
        'id' => null,
        'next_attempt_at' => null,
        'payload_hash' => null,
        'received_at' => null,
        'source_id' => null,
        'status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'account_id' => false,
        'attempts_count' => false,
        'body' => false,
        'created_at' => false,
        'created_by' => false,
        'direction' => false,
        'event_type' => false,
        'external_event_id' => false,
        'final_state' => false,
        'headers' => false,
        'id' => false,
        'next_attempt_at' => false,
        'payload_hash' => false,
        'received_at' => false,
        'source_id' => false,
        'status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'account_id',
        'attempts_count' => 'attempts_count',
        'body' => 'body',
        'created_at' => 'created_at',
        'created_by' => 'created_by',
        'direction' => 'direction',
        'event_type' => 'event_type',
        'external_event_id' => 'external_event_id',
        'final_state' => 'final_state',
        'headers' => 'headers',
        'id' => 'id',
        'next_attempt_at' => 'next_attempt_at',
        'payload_hash' => 'payload_hash',
        'received_at' => 'received_at',
        'source_id' => 'source_id',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'attempts_count' => 'setAttemptsCount',
        'body' => 'setBody',
        'created_at' => 'setCreatedAt',
        'created_by' => 'setCreatedBy',
        'direction' => 'setDirection',
        'event_type' => 'setEventType',
        'external_event_id' => 'setExternalEventId',
        'final_state' => 'setFinalState',
        'headers' => 'setHeaders',
        'id' => 'setId',
        'next_attempt_at' => 'setNextAttemptAt',
        'payload_hash' => 'setPayloadHash',
        'received_at' => 'setReceivedAt',
        'source_id' => 'setSourceId',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'attempts_count' => 'getAttemptsCount',
        'body' => 'getBody',
        'created_at' => 'getCreatedAt',
        'created_by' => 'getCreatedBy',
        'direction' => 'getDirection',
        'event_type' => 'getEventType',
        'external_event_id' => 'getExternalEventId',
        'final_state' => 'getFinalState',
        'headers' => 'getHeaders',
        'id' => 'getId',
        'next_attempt_at' => 'getNextAttemptAt',
        'payload_hash' => 'getPayloadHash',
        'received_at' => 'getReceivedAt',
        'source_id' => 'getSourceId',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('attempts_count', $data ?? [], null);
        $this->setIfExists('body', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('created_by', $data ?? [], null);
        $this->setIfExists('direction', $data ?? [], null);
        $this->setIfExists('event_type', $data ?? [], null);
        $this->setIfExists('external_event_id', $data ?? [], null);
        $this->setIfExists('final_state', $data ?? [], null);
        $this->setIfExists('headers', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('next_attempt_at', $data ?? [], null);
        $this->setIfExists('payload_hash', $data ?? [], null);
        $this->setIfExists('received_at', $data ?? [], null);
        $this->setIfExists('source_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['account_id'] === null) {
            $invalidProperties[] = "'account_id' can't be null";
        }
        if ($this->container['attempts_count'] === null) {
            $invalidProperties[] = "'attempts_count' can't be null";
        }
        if ($this->container['body'] === null) {
            $invalidProperties[] = "'body' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['direction'] === null) {
            $invalidProperties[] = "'direction' can't be null";
        }
        if ($this->container['headers'] === null) {
            $invalidProperties[] = "'headers' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['received_at'] === null) {
            $invalidProperties[] = "'received_at' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return string
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string $account_id account_id
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets attempts_count
     *
     * @return int
     */
    public function getAttemptsCount()
    {
        return $this->container['attempts_count'];
    }

    /**
     * Sets attempts_count
     *
     * @param int $attempts_count attempts_count
     *
     * @return self
     */
    public function setAttemptsCount($attempts_count)
    {
        if (is_null($attempts_count)) {
            throw new \InvalidArgumentException('non-nullable attempts_count cannot be null');
        }
        $this->container['attempts_count'] = $attempts_count;

        return $this;
    }

    /**
     * Gets body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param string $body body
     *
     * @return self
     */
    public function setBody($body)
    {
        if (is_null($body)) {
            throw new \InvalidArgumentException('non-nullable body cannot be null');
        }
        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets created_by
     *
     * @return string|null
     */
    public function getCreatedBy()
    {
        return $this->container['created_by'];
    }

    /**
     * Sets created_by
     *
     * @param string|null $created_by created_by
     *
     * @return self
     */
    public function setCreatedBy($created_by)
    {
        if (is_null($created_by)) {
            throw new \InvalidArgumentException('non-nullable created_by cannot be null');
        }
        $this->container['created_by'] = $created_by;

        return $this;
    }

    /**
     * Gets direction
     *
     * @return \Gethook\Model\Direction
     */
    public function getDirection()
    {
        return $this->container['direction'];
    }

    /**
     * Sets direction
     *
     * @param \Gethook\Model\Direction $direction direction
     *
     * @return self
     */
    public function setDirection($direction)
    {
        if (is_null($direction)) {
            throw new \InvalidArgumentException('non-nullable direction cannot be null');
        }
        $this->container['direction'] = $direction;

        return $this;
    }

    /**
     * Gets event_type
     *
     * @return string|null
     */
    public function getEventType()
    {
        return $this->container['event_type'];
    }

    /**
     * Sets event_type
     *
     * @param string|null $event_type event_type
     *
     * @return self
     */
    public function setEventType($event_type)
    {
        if (is_null($event_type)) {
            throw new \InvalidArgumentException('non-nullable event_type cannot be null');
        }
        $this->container['event_type'] = $event_type;

        return $this;
    }

    /**
     * Gets external_event_id
     *
     * @return string|null
     */
    public function getExternalEventId()
    {
        return $this->container['external_event_id'];
    }

    /**
     * Sets external_event_id
     *
     * @param string|null $external_event_id external_event_id
     *
     * @return self
     */
    public function setExternalEventId($external_event_id)
    {
        if (is_null($external_event_id)) {
            throw new \InvalidArgumentException('non-nullable external_event_id cannot be null');
        }
        $this->container['external_event_id'] = $external_event_id;

        return $this;
    }

    /**
     * Gets final_state
     *
     * @return string|null
     */
    public function getFinalState()
    {
        return $this->container['final_state'];
    }

    /**
     * Sets final_state
     *
     * @param string|null $final_state final_state
     *
     * @return self
     */
    public function setFinalState($final_state)
    {
        if (is_null($final_state)) {
            throw new \InvalidArgumentException('non-nullable final_state cannot be null');
        }
        $this->container['final_state'] = $final_state;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return array<string,mixed>
     */
    public function getHeaders()
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param array<string,mixed> $headers headers
     *
     * @return self
     */
    public function setHeaders($headers)
    {
        if (is_null($headers)) {
            throw new \InvalidArgumentException('non-nullable headers cannot be null');
        }
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets next_attempt_at
     *
     * @return string|null
     */
    public function getNextAttemptAt()
    {
        return $this->container['next_attempt_at'];
    }

    /**
     * Sets next_attempt_at
     *
     * @param string|null $next_attempt_at next_attempt_at
     *
     * @return self
     */
    public function setNextAttemptAt($next_attempt_at)
    {
        if (is_null($next_attempt_at)) {
            throw new \InvalidArgumentException('non-nullable next_attempt_at cannot be null');
        }
        $this->container['next_attempt_at'] = $next_attempt_at;

        return $this;
    }

    /**
     * Gets payload_hash
     *
     * @return string|null
     */
    public function getPayloadHash()
    {
        return $this->container['payload_hash'];
    }

    /**
     * Sets payload_hash
     *
     * @param string|null $payload_hash payload_hash
     *
     * @return self
     */
    public function setPayloadHash($payload_hash)
    {
        if (is_null($payload_hash)) {
            throw new \InvalidArgumentException('non-nullable payload_hash cannot be null');
        }
        $this->container['payload_hash'] = $payload_hash;

        return $this;
    }

    /**
     * Gets received_at
     *
     * @return string
     */
    public function getReceivedAt()
    {
        return $this->container['received_at'];
    }

    /**
     * Sets received_at
     *
     * @param string $received_at received_at
     *
     * @return self
     */
    public function setReceivedAt($received_at)
    {
        if (is_null($received_at)) {
            throw new \InvalidArgumentException('non-nullable received_at cannot be null');
        }
        $this->container['received_at'] = $received_at;

        return $this;
    }

    /**
     * Gets source_id
     *
     * @return string|null
     */
    public function getSourceId()
    {
        return $this->container['source_id'];
    }

    /**
     * Sets source_id
     *
     * @param string|null $source_id source_id
     *
     * @return self
     */
    public function setSourceId($source_id)
    {
        if (is_null($source_id)) {
            throw new \InvalidArgumentException('non-nullable source_id cannot be null');
        }
        $this->container['source_id'] = $source_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Gethook\Model\EventStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Gethook\Model\EventStatus $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


