<?php
/**
 * EventStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gethook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GetHook API
 *
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gethook\Model;
use \Gethook\ObjectSerializer;

/**
 * EventStatus Class Doc Comment
 *
 * @category Class
 * @package  Gethook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventStatus
{
    /**
     * Possible values of this enum
     */
    public const STATUS_RECEIVED = 'received';

    public const STATUS_ACCEPTED = 'accepted';

    public const STATUS_QUEUED = 'queued';

    public const STATUS_DELIVERING = 'delivering';

    public const STATUS_DELIVERED = 'delivered';

    public const STATUS_RETRY_SCHEDULED = 'retry_scheduled';

    public const STATUS_DEAD_LETTER = 'dead_letter';

    public const STATUS_REPLAYED = 'replayed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STATUS_RECEIVED,
            self::STATUS_ACCEPTED,
            self::STATUS_QUEUED,
            self::STATUS_DELIVERING,
            self::STATUS_DELIVERED,
            self::STATUS_RETRY_SCHEDULED,
            self::STATUS_DEAD_LETTER,
            self::STATUS_REPLAYED
        ];
    }
}


