<?php
/**
 * PlatformStats
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Gethook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GetHook API
 *
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Gethook\Model;

use \ArrayAccess;
use \Gethook\ObjectSerializer;

/**
 * PlatformStats Class Doc Comment
 *
 * @category Class
 * @package  Gethook
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PlatformStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PlatformStats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'delivery_attempts' => 'int',
        'events_delivered' => 'int',
        'events_processed' => 'int',
        'success_rate_pct' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'delivery_attempts' => null,
        'events_delivered' => null,
        'events_processed' => null,
        'success_rate_pct' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'delivery_attempts' => false,
        'events_delivered' => false,
        'events_processed' => false,
        'success_rate_pct' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'delivery_attempts' => 'delivery_attempts',
        'events_delivered' => 'events_delivered',
        'events_processed' => 'events_processed',
        'success_rate_pct' => 'success_rate_pct'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'delivery_attempts' => 'setDeliveryAttempts',
        'events_delivered' => 'setEventsDelivered',
        'events_processed' => 'setEventsProcessed',
        'success_rate_pct' => 'setSuccessRatePct'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'delivery_attempts' => 'getDeliveryAttempts',
        'events_delivered' => 'getEventsDelivered',
        'events_processed' => 'getEventsProcessed',
        'success_rate_pct' => 'getSuccessRatePct'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('delivery_attempts', $data ?? [], null);
        $this->setIfExists('events_delivered', $data ?? [], null);
        $this->setIfExists('events_processed', $data ?? [], null);
        $this->setIfExists('success_rate_pct', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets delivery_attempts
     *
     * @return int|null
     */
    public function getDeliveryAttempts()
    {
        return $this->container['delivery_attempts'];
    }

    /**
     * Sets delivery_attempts
     *
     * @param int|null $delivery_attempts delivery_attempts
     *
     * @return self
     */
    public function setDeliveryAttempts($delivery_attempts)
    {
        if (is_null($delivery_attempts)) {
            throw new \InvalidArgumentException('non-nullable delivery_attempts cannot be null');
        }
        $this->container['delivery_attempts'] = $delivery_attempts;

        return $this;
    }

    /**
     * Gets events_delivered
     *
     * @return int|null
     */
    public function getEventsDelivered()
    {
        return $this->container['events_delivered'];
    }

    /**
     * Sets events_delivered
     *
     * @param int|null $events_delivered events_delivered
     *
     * @return self
     */
    public function setEventsDelivered($events_delivered)
    {
        if (is_null($events_delivered)) {
            throw new \InvalidArgumentException('non-nullable events_delivered cannot be null');
        }
        $this->container['events_delivered'] = $events_delivered;

        return $this;
    }

    /**
     * Gets events_processed
     *
     * @return int|null
     */
    public function getEventsProcessed()
    {
        return $this->container['events_processed'];
    }

    /**
     * Sets events_processed
     *
     * @param int|null $events_processed events_processed
     *
     * @return self
     */
    public function setEventsProcessed($events_processed)
    {
        if (is_null($events_processed)) {
            throw new \InvalidArgumentException('non-nullable events_processed cannot be null');
        }
        $this->container['events_processed'] = $events_processed;

        return $this;
    }

    /**
     * Gets success_rate_pct
     *
     * @return float|null
     */
    public function getSuccessRatePct()
    {
        return $this->container['success_rate_pct'];
    }

    /**
     * Sets success_rate_pct
     *
     * @param float|null $success_rate_pct success_rate_pct
     *
     * @return self
     */
    public function setSuccessRatePct($success_rate_pct)
    {
        if (is_null($success_rate_pct)) {
            throw new \InvalidArgumentException('non-nullable success_rate_pct cannot be null');
        }
        $this->container['success_rate_pct'] = $success_rate_pct;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


